### PR TITLE
exclude Out from json marshalling in Operation

### LINKED ISSUE #47: Operation struct includes Out field when marshaled to son
The Out field is an io.writer, including it in json serialization means that CNAB-go cannot be used to implement a duffle command driver as unmarshall of {} fails.

### PR DESCRIPTION
**Pull request by simongdavies**
fixes #47.

@jeremyrickard , @silvin-lubecki this replace #48 , now has marshall/unmarshall tests

### CODE REVIEW

File: driver/driver_test.go [hunk 1]
```diff
@@ -30,3 +32,49 @@ func TestDebugDriver_Run(t *testing.T) {
...
+	var op Operation
+	is := assert.New(t)
+	bytes, err := ioutil.ReadFile("../testdata/operations/valid-operation.json")
+	is.NoError(err, "Error reading from testdata/operations/valid-operation.json")
+	is.NoError(json.Unmarshal(bytes, &op), "Error unmarshalling operation")
+	is.NotNil(op, "Expected Operation not to be nil")
+}
+
+func TestOperation_Marshall(t *testing.T) {
+
```
Comment (silvin-lubecki) [inline driver/driver_test.go]: nit: empty line

File: driver/driver_test.go [hunk 2]
```diff
@@ -30,3 +32,49 @@ func TestDebugDriver_Run(t *testing.T) {
...
 	is.NoError(d.Run(op))
 }
+
+func TestOperation_Unmarshall(t *testing.T) {
+	var op Operation
+	is := assert.New(t)
+	bytes, err := ioutil.ReadFile("../testdata/operations/valid-operation.json")
+	is.NoError(err, "Error reading from testdata/operations/valid-operation.json")
+	is.NoError(json.Unmarshal(bytes, &op), "Error unmarshalling operation")
+	is.NotNil(op, "Expected Operation not to be nil")
```
Comment (silvin-lubecki) [inline driver/driver_test.go]: Could you test with a `DeepEqual` instead? So you are sure the unmarshalled struct is valid.

File: driver/driver_test.go [hunk 3]
```diff
@@ -30,3 +32,49 @@ func TestDebugDriver_Run(t *testing.T) {
...
+		},
+		Out: os.Stdout,
+	}
+	is := assert.New(t)
+	bytes, err := json.Marshal(actualOp)
+	is.NoError(err, "Error Marshalling actual operation to json")
+	is.NotNil(bytes, "Expected marshalled json not to be nil")
+	actualJSON := string(bytes)
+	var expectedOp Operation
+	bytes, err = ioutil.ReadFile("../testdata/operations/valid-operation.json")
```
Comment (silvin-lubecki) [inline driver/driver_test.go]: Why don't you just check the equality between those bytes and the actualJSON bytes?

Comment (simongdavies) [reply driver/driver_test.go]: I did it this way so that I don't have to worry about the formatting of the json, if the way that operation is serialized changes then this will still work. I guess I could have minified the json and compared those bytes but this didn't require any additional libs.

Comment (carolynvs) [reply driver/driver_test.go]: Speaking as someone who just had to work with a test in cnab-go that asserted on the bytes instead of the json string representation, comparing strings instead of bytes is also a lot easier to deal with when the test fails or needs to be updated.
